// tests/pass-qr-hook.test.ts — the booking pass's QR code as PocketBase draws
// it for the guest e-mails (pb_hooks/lib/passqr.js, with the app's `qr`
// library bundled into pb_hooks/lib/vendor/qr.js by npm run vendor:pb-qr).
// It has to be the same picture as the app's qr.png, which Telegram gets, and
// the bundle has to follow `qr` when it is updated. In a real e-mail:
// tests/integration/notifications.test.ts.
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import { HOOKS_DIR, loadHookModule } from './hook-module';
import { decodeQrPng, pngChunks, readMonochromePng } from './stack-helpers';
import { passQrPng as appPassQrPng, passUrl } from '../src/lib/server/pass';

// The JSVM has no TextEncoder, no zlib and no Buffer; neither has this context.
const passqr = loadHookModule('lib/passqr.js', { TextEncoder: undefined });

const URLS = [
	passUrl('https://cozynights.hamburn.de', '7F3K9QXM2CWD'),
	passUrl('https://test-cozynights.hamburn.de', 'ABCDEFGHJKMN'),
	passUrl('http://127.0.0.1:3290', 'AAAABBBBCCCC'),
	// a longer link makes a bigger QR code: more modules, the same rules
	'https://cozynights.hamburn.de/pass/7F3K-9QXM-2CWD?from=a-very-long-campaign-name-0123456789'
];

const png = (url: string) => Buffer.from(passqr.passQrPng(url) as number[]);

describe('the pass QR picture drawn in PocketBase', () => {
	it('is a valid 1-bit greyscale PNG of 410 × 410 pixels for a pass link', () => {
		const bytes = png(URLS[0]);
		const chunks = pngChunks(bytes);
		expect(chunks.map((c) => c.type)).toEqual(['IHDR', 'IDAT', 'IEND']);
		for (const chunk of chunks) {
			const typeAndData = Buffer.concat([Buffer.from(chunk.type, 'ascii'), chunk.data]);
			expect(zlib.crc32(typeAndData), chunk.type).toBe(chunk.crc);
		}
		const image = readMonochromePng(bytes);
		expect([image.width, image.height]).toEqual([410, 410]);
		// what an e-mail carries: a plain array of byte values, about 22 KB
		const values = passqr.passQrPng(URLS[0]) as number[];
		expect(Array.isArray(values)).toBe(true);
		expect(values.every((b) => Number.isInteger(b) && b >= 0 && b < 256)).toBe(true);
		expect(bytes.length).toBeLessThan(25_000);
	});

	it('has the same pixels as the qr.png of the app, for every link', () => {
		for (const url of URLS) {
			const mine = readMonochromePng(png(url));
			const app = readMonochromePng(appPassQrPng(url));
			expect([mine.width, mine.height], url).toEqual([app.width, app.height]);
			expect(mine.rows.equals(app.rows), url).toBe(true);
		}
	});

	it('encodes text beyond ASCII like the app (UTF-8 without TextEncoder)', () => {
		const url = 'https://cozy.test/pass/Grüße-€-🔥';
		expect(readMonochromePng(png(url)).rows.equals(readMonochromePng(appPassQrPng(url)).rows)).toBe(
			true
		);
	});

	it('reads back as the pass link', () => {
		for (const url of URLS) expect(decodeQrPng(png(url))).toBe(url);
	});

	it('draws another scale on request', () => {
		const small = readMonochromePng(png(URLS[0]));
		const bigger = readMonochromePng(Buffer.from(passqr.passQrPng(URLS[0], 12) as number[]));
		expect(passqr.PASS_QR_SCALE).toBe(10);
		expect(small.width).toBe(41 * 10);
		expect(bigger.width).toBe(41 * 12);
	});

	it('turns into a data: URI for the admin preview', () => {
		const bytes = passqr.passQrPng(URLS[0]) as number[];
		const uri = passqr.dataUri(bytes) as string;
		expect(uri).toMatch(/^data:image\/png;base64,[A-Za-z0-9+/]+={0,2}$/);
		expect(Buffer.from(uri.split(',')[1], 'base64').equals(Buffer.from(bytes))).toBe(true);
		// every padding case of base64
		for (const n of [0, 1, 2, 3, 4, 5]) {
			const some = Array.from({ length: n }, (_, i) => (i * 97 + 200) & 255);
			expect(passqr.dataUri(some)).toBe(
				'data:image/png;base64,' + Buffer.from(some).toString('base64')
			);
		}
	});
});

describe('the bundled qr library (pb_hooks/lib/vendor/qr.js)', () => {
	const bundle = fs.readFileSync(path.join(HOOKS_DIR, 'lib/vendor/qr.js'), 'utf8');
	const installed = JSON.parse(
		fs.readFileSync(path.join(HOOKS_DIR, '../node_modules/qr/package.json'), 'utf8')
	);

	it('is the version the app uses: after an update of qr, run npm run vendor:pb-qr', () => {
		const banner =
			/^\/\/ qr@(\S+) \(MIT OR Apache-2\.0, Paul Miller\) — generated by npm run vendor:pb-qr, do not edit\n/.exec(
				bundle
			);
		expect(banner, 'the first line of pb_hooks/lib/vendor/qr.js').not.toBeNull();
		expect(banner![1]).toBe(installed.version);
	});

	it('comes with its license', () => {
		expect(bundle).toContain('Copyright (c) 2023 Paul Miller');
		const license = fs.readFileSync(path.join(HOOKS_DIR, 'lib/vendor/LICENSE-qr'), 'utf8');
		expect(license).toContain('The MIT License');
		expect(license).toContain('Paul Miller');
	});
});
