// scripts/vendor-pb-qr.mjs — copies the app's `qr` library into pb_hooks, so
// PocketBase can draw the booking pass's QR code for the guest e-mails itself
// (pb_hooks/lib/passqr.js). The JSVM only loads CommonJS files from disk and
// has no npm, so the ES module from node_modules is bundled into one plain
// script: readable, not minified, so a review can see what runs there.
//
//   npm run vendor:pb-qr
//
// Run it again whenever `qr` is updated in package.json (Dependabot):
// tests/pass-qr-hook.test.ts fails while the bundle's version differs from
// node_modules/qr, and checks that both draw the same pixels. The output and
// LICENSE-qr are committed; never edit them by hand.
//
// esbuild is not a dependency of this package itself: it is installed with
// vite 7, which uses it. Should a vite update stop bringing it along, add
// esbuild to the devDependencies.
import { build } from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const qrDir = path.join(root, 'node_modules/qr');
const outDir = path.join(root, 'pb_hooks/lib/vendor');
const pkg = JSON.parse(fs.readFileSync(path.join(qrDir, 'package.json'), 'utf8'));
// "(MIT OR Apache-2.0)" → "MIT OR Apache-2.0", it goes into parentheses below
const license = String(pkg.license).replace(/^\((.*)\)$/, '$1');

fs.mkdirSync(outDir, { recursive: true });
await build({
	absWorkingDir: root,
	entryPoints: [path.join(qrDir, 'index.js')],
	outfile: path.join(outDir, 'qr.js'),
	bundle: true,
	// goja, PocketBase's JS engine, is ES5.1 plus most of ES2015+: es2017
	// lowers what newer syntax the library uses
	format: 'cjs',
	target: 'es2017',
	legalComments: 'inline',
	logLevel: 'warning',
	banner: {
		js: `// qr@${pkg.version} (${license}, Paul Miller) — generated by npm run vendor:pb-qr, do not edit`
	}
});
// MIT OR Apache-2.0: shipped under the MIT license, whose text has to come along
fs.copyFileSync(path.join(qrDir, 'LICENSE-MIT'), path.join(outDir, 'LICENSE-qr'));

const size = fs.statSync(path.join(outDir, 'qr.js')).size;
console.log(`pb_hooks/lib/vendor/qr.js: qr@${pkg.version}, ${(size / 1024).toFixed(1)} KB`);
